WITH DT_SILVER AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.UNIT_PRICE,
        COUNT(DISTINCT K.ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT K.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
        SUM(STG.QUANTITY) AS TOTAL_QUANTITY_SOLD,
        SUM(STG.TOTAL_AMOUNT) AS TOTAL_REVENUE,
        AVG(STG.QUANTITY) AS AVG_QUANTITY_PER_ORDER
    FROM
        {{ ref('dt_products') }} P
    INNER JOIN
        {{ ref('dt_key') }} K
        ON P.PRODUCT_ID = K.PRODUCT_ID
    INNER JOIN
        {{ ref('dt_orders') }} O
        ON K.ORDER_ID = O.ORDER_ID
    INNER JOIN
        {{ ref('dt_stg_orders') }} STG
        ON K.ORDER_ID = STG.ORDER_ID
        AND K.CUSTOMER_ID = STG.CUSTOMER_ID
        AND K.PRODUCT_ID = STG.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.UNIT_PRICE
)
SELECT
    *,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    CURRENT_DATE() AS LOAD_DATE_DAY,
    TO_VARCHAR(CURRENT_DATE(),'YYYY-MM') AS LOAD_DATE_MONTH
FROM
    DT_SILVER

