WITH DT_SILVER AS (
    SELECT
        C.CUSTOMER_ID,
        C.REGION,
        C.CUSTOMER_SEGMENT,
        COUNT(DISTINCT K.ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT K.PRODUCT_ID) AS TOTAL_PRODUCTS,
        SUM(STG.TOTAL_AMOUNT) AS TOTAL_REVENUE,
        AVG(STG.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
        MIN(O.ORDER_DATE) AS FIRST_ORDER_DATE,
        MAX(O.ORDER_DATE) AS LAST_ORDER_DATE
    FROM
        {{ ref('dt_customers') }} C
    INNER JOIN
        {{ ref('dt_key') }} K
        ON C.CUSTOMER_ID = K.CUSTOMER_ID
    INNER JOIN
        {{ ref('dt_orders') }} O
        ON K.ORDER_ID = O.ORDER_ID
    INNER JOIN
        {{ ref('dt_stg_orders') }} STG
        ON K.ORDER_ID = STG.ORDER_ID
        AND K.CUSTOMER_ID = STG.CUSTOMER_ID
        AND K.PRODUCT_ID = STG.PRODUCT_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.REGION,
        C.CUSTOMER_SEGMENT
)
SELECT
    *,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    CURRENT_DATE() AS LOAD_DATE_DAY,
    TO_VARCHAR(CURRENT_DATE(),'YYYY-MM') AS LOAD_DATE_MONTH
FROM
    DT_SILVER

