WITH DT_BRONZE AS (
    SELECT
        DISTINCT
         CUSTOMER_ID,
         REGION,
         CUSTOMER_SEGMENT
    FROM
        {{ ref('dt_stg_orders') }}
)
SELECT
    *,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    CURRENT_DATE() AS LOAD_DATE_DAY,
    TO_VARCHAR(CURRENT_DATE(),'YYYY-MM') AS LOAD_DATE_MONTH
FROM
    DT_BRONZE
GROUP BY
    CUSTOMER_ID,
    REGION,
    CUSTOMER_SEGMENT

